# Generated by Django 4.2.2 on 2023-08-05 17:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acerca',
            name='descripcion',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
    ]
